### ISSUE TITLE
Custom API

### ISSUE THREAD

**Issue by rutger1337** [wesselperik/saxionroosters#4]
We need a fancy api for the schedule app. 

http://onelink.to/savq3f

**Comment by wesselperik** [comment]
Which functions do we want in a custom API?

A few suggestions:
- option to create a custom schedule (for students who don't follow all lectures, edit a current schedule)
- room schedules (see Ruud's [Roosterious](https://roosterious.com/) project)

**Comment by Max053** [comment]
I think it would be nice to have an endpoint that returns changed lectures since a specific datetime for a specific student/class/teacher.

**Comment by wesselperik** [comment]
Created a new repository for the API: https://github.com/wesselperik/saxionroosters-api
